repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: no-commit-to-branch
    args: ['--branch', 'main']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.0
  hooks:
  - id: ruff
    args: ['--ignore=E741,E501', '--extend-exclude=subprojects', '.']
  - id: ruff-format
    args: ['--check', '--diff']
- repo: https://gitlab.freedesktop.org/freedesktop/ci-templates.git
  rev: 7402203527f61d6473d55ad701172d1606508c52
  hooks:
  - id: check-commits
  - id: generate-template
